### ISSUE TITLE
base_tsa: Fix crash after Ctrl-Alt-Del in all games since th11

### ISSUE THREAD

**Issue by nmlgc** [thpatch/thcrap-tsa#1]

**Comment by DankRank** [comment]
A while ago I've tried to fix this bug, but I didn't succeed. My guess was that the game doesn't handle [lost devices](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174714(v=vs.85).aspx) the right way. It seems like the game indeed doesn't do it properly, but it isn't a problem most of the time, because modern versions of d3d9 don't lose device when you alt-tab or alt-enter, etc. It still happens, however, when you do win+L or ctrl+alt+del. That's not the actual reason though, after applying my fix, the game still crashes somewhere around texture (re)initialization.

One thing I haven't got around to test is wether or not the game will crash under XP (with original d3d9 installed) when alt-tabbing from full screen.

Here's the aforementioned fix: DankRank/thcrap@42e7b152
The BP_devicelost is supposed to replace a call to IDirect3DDevice9::Reset.

p.s. Everything I mention applies to LoLK, as I haven't looked at the other games (except DDC), but I'd assume that the problem is same.
p.p.s. I will post relevant memory locations for LoLK (and maybe DDC, if I still have those saved) later.

**Comment by DankRank** [comment]
Found my old stuff for LoLK v1.00b

stack trace:
```
0044F349 - crash happens here (inside sub_44F300)
called at 00472981 (inside sub_472940)
called at 00472913 (inside sub_472790)
called at 00471AB7 (inside sub_471340, looks like WinMain)
```
---
Patch for the BP_devicelost, mentioned in previous post.
th15.js
```json
{
	"breakpoints": {
		"devicelost": {
			"cavesize": "5"
		}
	}
}
```

th15.v1.00b.js
```json
{
	"breakpoints":{
		"devicelost":{
			"addr": "Rx72972"
		}
	}
}
```

**Comment by DankRank** [comment]
2edbcc1be066cc2259c928e3cbe5cee4fde6bff6 fixes this for all latest versions

**Comment by DankRank** [comment]
Reopening, since the fix doesn't work on all machines apparently.

**Comment by DankRank** [comment]
Should be fixed as of thpatch/thcrap@cb3404cdd

**Comment by DankRank** [comment]
Fixed the fullscreen switching in thpatch/thcrap@c807a61ba0

Works on my machine, stops working on @nmlgc 's machine after switching fullscreen to window.

**Comment by nmlgc** [comment]
Turned out to be a graphics driver issue on my end, and no remaining bugs in here after all.

In case anyone else has a similar issue with a AMD Radeon GPU (R7 260X in my case): TH14 and later used to not be displayed correctly in fullscreen mode. On startup, the screen flashed for a few seconds as Direct3D tried to change the display mode and failed. After that, the game was rendered at its native resolution in the top-left corner of my first monitor, with the rest of the screen filled with black, like this:

![th14_046](https://user-images.githubusercontent.com/2139424/30886579-d25eb822-a317-11e7-93e6-704e63c217dc.png)

The fix: Catalyst Control Center → My Digital Flat-Planels → (the display Touhou appears on) → Image Scaling Prefences → Disable GPU up-scaling.
![th14 amd fullscreen bug culprit](https://user-images.githubusercontent.com/2139424/30886312-e0a0d1dc-a316-11e7-87d9-d7d7c49f7042.png)
