### ISSUE TITLE
TH09: Why is this font wrong?

### ISSUE THREAD

**Issue by webbedspace** [thpatch/thcrap-tsa#50]
![2022-03-08 12 52 32 AM - Touhou_Flower_Reflecting_Mound_~_Phantasmagoria_of](https://user-images.githubusercontent.com/83939/157060233-53a01f59-a85e-44b4-b2d2-fdb5be7f25f6.png)
This seems to be a normal install, but the font in these dialogs is too wide. (Shouldn't it be that Cirno font or something?) Problem is the same regardless of JP or US locale, or the use of thpatch or vpatch.

**Comment by brliron** [comment]
On the technical side, lang_en has a file that switches the font to Aroania: https://browse.thpatch.net/lang_en/th09.js . I can't find the page that generates this file, but if we want to change the font, I can try a few things.

But outside of that, no font is right or wrong, only choices. For this font, you could say that it's too wide, or you could say that it looks better. I personally prefer to avoid taking part in these kind of choices, and intentional or not, it's a fact that th09 uses this font today, so I'd like to ask our community about this before changing anything.

If you want to see the discussion or take part of it, you can join our Discord on https://discord.thpatch.net/ , I'll talk about it in #sprites

**Comment by brliron** [comment]
I changed the font back to Cirno
